config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :slot_bookings do
    member do
      patch 'cancel'
    end
    collection do
      get 'allocation_history'
      get 'first_entry'
      get 'my_bookings'
      get 'used_slots'
    end
  end

  root to: 'slot_bookings#index'
end

app/models/slot_booking.rb
class SlotBooking < ApplicationRecord
  belongs_to :entry_point
  belongs_to :slot

  validates_presence_of :entry_point

  validates :vehicle_registration_number, presence: true, format: { with: /\A[a-zA-Z0-9 ]+\z/, message: "No special characters allowed" }
  validate :vehicle_can_enter_once_per_day, on: :create


  def vehicle_can_enter_once_per_day
    if SlotBooking.exists?(vehicle_registration_number: vehicle_registration_number, entry_time: entry_time.beginning_of_day..entry_time.end_of_day)
      errors.add(:base, 'Vehicle can enter the parking only once per day')
    end
  end

  def cancel
    return false if canceled?
    Slot.transaction do
      update(canceled: true, canceled_at: Time.zone.now)
      slot.update(occupied: false)
    end
    true
  end

  scope :used_on_date, ->(date) { where(entry_time: date.beginning_of_day..date.end_of_day) }

  scope :history, ->(vehicle_number) { where(vehicle_registration_number: vehicle_number) }

end

app/controllers/slot_bookings_controller.rb
class SlotBookingsController < ApplicationController
  before_action :set_entry_points, only: [:new, :create]
  before_action :set_slot, only: [:show, :cancel]

  def index
  end

  def new
    @slot_booking = SlotBooking.new
  end

  def show
  end

  def create
    @slot_booking = SlotBooking.new(slot_booking_params)
    @slot_booking.entry_time = Time.now
    @slot_booking.user_id = current_user.id

    if @slot_booking.entry_point.present?
      nearest_slot = find_nearest_available_slot(@slot_booking.entry_point)

      if nearest_slot
        @slot_booking.slot = nearest_slot
        nearest_slot.update(occupied: true)
        respond_to do |format|
          if @slot_booking.save
            format.html { redirect_to slot_booking_path(@slot_booking), notice: "Slot booked successfully! Your nearest slot is #{nearest_slot.number}." }
          else
            format.html { render :new, status: :unprocessable_entity, alert: "Failed to book the slot" }
          end
        end
      else
        render :new, status: :unprocessable_entity, alert: "No slots available at the moment"
      end
    else
      render :new, alert: "Entry point must present"
    end
  end

  def cancel
    respond_to do |format|
      if @slot_booking.cancel
        format.html { redirect_to my_bookings_slot_bookings_path, notice: "Slot booking has been canceled successfully." }
      else
        format.html { redirect_to my_bookings_slot_bookings_path, alert: "Unable to cancel the slot booking." }
      end
    end
  end

  def used_slots
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @pagy, @slot_bookings = pagy(SlotBooking.includes(:slot).used_on_date(@date), items: 5)
  end

  def allocation_history
    @vehicle_number = params[:vehicle_number]
    @pagy, @slot_bookings = pagy(SlotBooking.includes(:slot).history(@vehicle_number))
  end

  def first_entry
    @pagy, @slot_bookings = pagy(SlotBooking.select("MIN(entry_time) AS first_entry_time, vehicle_registration_number").group(:vehicle_registration_number), items: 8)
  end

  def my_bookings
    @pagy, @slot_bookings = pagy(SlotBooking.includes(:slot).where(user_id: current_user.id))
  end


  private

  def set_entry_points
    @entry_points = EntryPoint.all
  end

  def set_slot
    @slot_booking = SlotBooking.find(params[:id])
  end

  def slot_booking_params
    params.require(:slot_booking).permit(:entry_point_id, :vehicle_registration_number)
  end

  def find_nearest_available_slot(entry_point)
    available_slots = Slot.where(occupied: false)
    nearest_slot = nil
    nearest_distance = nil

    available_slots.each do |slot|
      distance = Geocoder::Calculations.distance_between(
        [entry_point.latitude, entry_point.longitude],
        [slot.latitude, slot.longitude]
      )

      if nearest_distance.nil? || distance < nearest_distance
        nearest_slot = slot
        nearest_distance = distance
      end
    end

    nearest_slot
  end

end

app/helpers/slot_bookings_helper.rb
module SlotBookingsHelper
end

app/views/slot_bookings/allocation_history.html.erb
<h1 style="text-align: center">Allocation history</h1>

<%= form_tag(allocation_history_slot_bookings_path , method: :get) do %>
  <div class="field">
    <%= label_tag 'vehicle_number', 'Enter a vehicle number:' %>
    <%= text_field_tag 'vehicle_number', params[:vehicle_registration_number], class: "form-control-sm" %>
  </div>
  <br>
  <%= submit_tag 'Show History', class: "btn btn-primary btn-sm" %>
<% end %>
<br>
<% if @slot_bookings.present? %>
  <h2>History of vehicle <%= @vehicle_number %>:</h2>
  <table class="table table-hover table-light" style="text-align: center" >
    <thead class="table-dark">
    <tr>
      <th>Entered Slot</th>
      <th>Entry Date</th>
      <th>Entry Time</th>
    </tr>
    </thead>
    <tbody>
    <% @slot_bookings.each do |slot_usage| %>
      <tr>
        <td><%= slot_usage.slot.number %></td>
        <td><%= slot_usage.entry_time.strftime('%B %d, %Y') %></td>
        <td><%= slot_usage.entry_time.strftime('%l:%M %p') %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No allocation history.</p>
<% end %>
<br>
<%= link_to "Back", slot_bookings_path, class: "btn btn-secondary" %>

<br>
<div class="pagination justify-content-center">
  <%= pagy_bootstrap_nav(@pagy).html_safe %>
</div>

app/views/slot_bookings/first_entry.html.erb
<h1 style="text-align: center">First Entries</h1>

<% if @slot_bookings.present? %>
  <table class="table table-hover table-light" style="text-align: center" >
    <thead class="table-dark">
    <tr>
      <th>Vehicle number</th>
      <th>Entry Date</th>
      <th>Entry Time</th>
    </tr>
    </thead>
    <tbody>
    <% @slot_bookings.each do |slot_usage| %>
      <tr>
        <td><%= slot_usage.vehicle_registration_number %></td>
        <td><%= slot_usage.first_entry_time.to_datetime.strftime('%B %d, %Y') %></td>
        <td><%= slot_usage.first_entry_time.to_datetime.strftime('%l:%M %p') %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No entries.</p>
<% end %>

<%= link_to "Back", slot_bookings_path, class: "btn btn-secondary" %>

<div class="pagination justify-content-center">
  <%= pagy_bootstrap_nav(@pagy).html_safe %>
</div>

app/views/slot_bookings/index.html.erb
<h1 style="text-align: center">Welcome to Parking Slot Booking!!!</h1>
<br><br>
<p style="text-align: center"><%= link_to "Book Now", new_slot_booking_path, class: "btn btn-primary" %></p>

app/views/slot_bookings/my_bookings.html.erb
<h1 style="text-align: center">My Bookings</h1>

<% if @slot_bookings.present? %>
  <table class="table table-hover table-light" style="text-align: center" >
    <thead class="table-dark">
    <tr>
      <th>Vehicle number</th>
      <th>Entered Slot</th>
      <th>Entry Date</th>
      <th>Entry Time</th>
      <th colspan="2"></th>
    </tr>
    </thead>
    <tbody>
    <% @slot_bookings.each do |slot_usage| %>
      <tr>
        <td><%= slot_usage.vehicle_registration_number %></td>
        <td><%= slot_usage.slot.number %></td>
        <td><%= slot_usage.entry_time.to_datetime.strftime('%B %d, %Y') %></td>
        <td><%= slot_usage.entry_time.to_datetime.strftime('%l:%M %p') %></td>
        <td><%= link_to "Show details", slot_booking_path(slot_usage), class: "btn btn-info btn-sm" %></td>
        <%if !slot_usage.canceled %>
          <td><%= button_to "Cancel", cancel_slot_booking_path(slot_usage), method: :patch, data: { confirm: "Are you sure you want to cancel this booking?" }, class: "btn btn-danger" %></td>
        <%else %>
          <td style="text-align: center" class="badge text-bg-secondary">canceled</td>
        <%end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No bookings yet.</p>
<% end %>

<br>
<%= link_to "Back", slot_bookings_path, class: "btn btn-secondary" %>

<br>
<div class="pagination justify-content-center">
  <%= pagy_bootstrap_nav(@pagy).html_safe %>
</div>

app/views/slot_bookings/new.html.erb
<h1 style="text-align: center">Book your slot !</h1>

<%= form_with model: @slot_booking, url: slot_bookings_path, method: :post do |form| %>
  <% if @slot_booking.errors.any? %>
    <div id="error_explanation" style="color: red">
      <ul>
        <% @slot_booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :entry_point_id, "Entrance number:" %><span style="color: red">*</span>
    <%= form.collection_select :entry_point_id, @entry_points, :id, :name, prompt: 'Select an entry point', class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= form.label :vehicle_registration_number, "Enter vehicle registration number:" %><span style="color: red">*</span>
    <%= form.text_field :vehicle_registration_number, class: "form-control-sm" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Book Slot", class: "btn btn-primary mb-3" %>
  </div>
<% end %>
<br><br>
<%= link_to "Back", slot_bookings_path, class: "btn btn-secondary" %>

app/views/slot_bookings/show.html.erb
<h1>Booking details</h1>
<div>
  <p>Entry point: <%= @slot_booking.entry_point_id %></p>
  <p>Entry time: <%= @slot_booking.entry_time.strftime('%B %d, %Y %l:%M %p') %></p>
  <p>Registration Number: <%= @slot_booking.vehicle_registration_number %></p>
  <p>Slot: <%= @slot_booking.slot_id %></p>
</div>
<%if !@slot_booking.canceled %>
  <%= button_to "Cancel booking", cancel_slot_booking_path(@slot_booking), method: :patch, data: { confirm: "Are you sure you want to cancel this booking?" }, class: "btn btn-danger" %>
<%else %>
  <p class="badge text-bg-secondary">Canceled !</p>
<%end %>

<br><br>
<br><br>
<%= link_to "Back",slot_bookings_path, class: "btn btn-secondary" %>

app/views/slot_bookings/used_slots.html.erb
<h1 style="text-align: center">Used Slots</h1>

<%= form_tag(used_slots_slot_bookings_path, method: :get) do %>
  <div class="field">
    <%= label_tag 'date', 'Select a Date:' %>
    <%= date_field_tag 'date', params[:date], class: "form-control-sm" %>
  </div>
  <br>
  <%= submit_tag 'Show Slots', class: "btn btn-primary btn-sm" %>
<% end %>
<br>
<% if @slot_bookings.present? %>
  <h2>Slots used on <%= @date %>:</h2>
  <table class="table table-hover table-light" style="text-align: center" >
    <thead class="table-dark">
    <tr>
      <th>Slot Number</th>
      <th>Vehicle Registration Number</th>
      <th>Status</th>
    </tr>
    </thead>
    <tbody>
    <% @slot_bookings.each do |slot_usage| %>
      <tr>
        <td><%= slot_usage.slot.number %></td>
        <td><%= slot_usage.vehicle_registration_number %></td>
        <%if slot_usage.canceled? %>
          <td class="badge text-bg-info">Canceled</td>
        <%else %>
          <td class="badge text-bg-info">In use</td>
        <%end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No slots used on the selected date.</p>
<% end %>
<br>
<%= link_to "Back", slot_bookings_path, class: "btn btn-secondary" %>

<br>
<div class="pagination justify-content-center">
  <%= pagy_bootstrap_nav(@pagy).html_safe %>
</div>