config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :slot_bookings do
    member do
      patch 'cancel'
    end
    collection do
      get 'allocation_history'
      get 'first_entry'
      get 'my_bookings'
      get 'used_slots'
    end
  end

  root to: 'slot_bookings#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" type="image/x-icon" href="https://cdn.iconscout.com/icon/free/png-512/free-car-1093-459261.png?f=avif&w=512">
    <title>Parking Slot Finder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>

  <body>

    <nav class="navbar bg-dark border-bottom border-body rounded" data-bs-theme="dark">
      <% if user_signed_in? %>
        <div class="navbar justify-content-left">
          <%= link_to 'Home', slot_bookings_path, class: 'navbar-link btn btn-dark'%>
          <%= link_to 'Book slot', new_slot_booking_path, class: 'navbar-link btn btn-dark'%>
          <%= link_to 'Used slots', used_slots_slot_bookings_path, class: 'navbar-link btn btn-dark' %>
          <%= link_to 'Allocation History', allocation_history_slot_bookings_path, class: 'navbar-link btn btn-dark' %>
          <%= link_to 'First entries', first_entry_slot_bookings_path, class: 'navbar-link btn btn-dark' %>
          <%= link_to "My bookings", my_bookings_slot_bookings_path, class: 'navbar-link btn btn-dark' %>
        </div>
        <div class="navbar justify-content-end">
          <span class="badge text-bg-light">Logged in as <strong><%= current_user.email %></strong>.</span>
          <div class="btn-group">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link btn btn-danger btn-sm"  %>
          </div>
      <% else %>
        <div class="navbar justify-content-end">
          <%= link_to "Sign up", new_user_registration_path, class: "navbar-link btn btn-secondary btn-sm"  %>
          <%= link_to "Login", new_user_session_path, class: "navbar-link btn btn-primary btn-sm"  %>
        </div>
      <% end %>
      </div>
    </nav>
    <br>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>